Add form
tombein/capstone-project pull request #13
Opened 2022-05-24 18:08 UTC by tombein

Add Form and Image

2022-05-25 08:34 UTC, anitaschiller requested changes
Hi Tom, good job.
I left some comments because I think there are some parts of your code which can be deleted.

2022-05-25 08:34 UTC, anitaschiller commented on pages/index.js
>  	const data = getCardMap();
I think you don't need those static props anymore since you get the card data from zustand.

2022-05-25 08:34 UTC, anitaschiller commented on pages/index.js
>  			<CardList postdata={data} />
The postdata prop can be deleted, too (see my last comment).

2022-05-25 08:34 UTC, anitaschiller commented on src/components/CardMap/CardList.js
> +			{cardlistzustand.map(angebot => {
I'd recommend to name all variables and object properties in english!

```suggestion
			{cardlistzustand.map(offer => {
```

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Cards/Cards.js
> +export default function Cards({ angebot }) {
Since your component renders only one single card, it would be easier to understand if the component's name was `Card.js` instead of `Cards.js`

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Form/Form.js
> +				}, */
Can be deleted! 😉

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Form/FormButton.js
> +export default function AddFormButton({ onSetFormButton }) {
Are you using this button anywhere? If not, the component can be deleted

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Form/FormButton.js
> +		<button type="button" onClick={() => onSetFormButton(prevCheck => !prevCheck)}>
I think `prevCheck` is undefined here.

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Form/RenderOffer.js
> +						{/* 	<Contact>Kontakt</Contact> */}
Can be deleted if you don't want to have it in there!

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Form/RenderOffer.js
> +export default function RenderOffer({ onAddPost }) {
Hmm looks a bit like your Card component but I'm not so sure what this component is supposed to be doing. Are you using it anywhere? I think it might be redundant and can be deleted?

2022-05-25 08:34 UTC, anitaschiller commented on src/hooks/useStore.js
> +				},
As already mentioned in a comment above I would recommend to name everything in english: 

```suggestion
				date: '13-10-2022',
				timeFrame: '17:15-17:30',
				amountBottles: '18',
				notes: 'Flaschen stehen im Treppenhaus',
				photo: {
					url: 'https://images.unsplash.com/photo-1653059959899-70ab4e464401?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
				},
```

2022-05-25 08:34 UTC, anitaschiller commented on src/hooks/useStore.js
> +		},
If you don't use it, please delete commented out code!

2022-05-25 08:34 UTC, anitaschiller commented on src/components/Cards/Cards.js
> +	console.log(angebot);
console.logs should be deleted before merging!

2022-05-27 11:53 UTC, UrsulaMontag approved these changes
Hey Tom, please look at my little comments before merging :-)

2022-05-27 11:53 UTC, UrsulaMontag commented on src/components/CardMap/CardList.js
> +			{cardlistzustand.map(angebot => {
Like Anita I would recommend to actually name ALL variables and object properties in english. angebot=offer

2022-05-27 11:53 UTC, UrsulaMontag commented on src/components/Form/Form.js
> +	const [anzahlflaschenValue, setAnzahlflaschenValue] = useState('');
Try to adapt your state names to your now english variable names, then this part will be more understandable.

2022-05-30 13:17 UTC, mikailsayan approved these changes

2022-05-31 11:41 UTC, merged